# Generated by Django 5.1.6 on 2025-02-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField()),
                ('items', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('в ожидании', 'В ожидании'), ('готово', 'Готово'), ('оплачено', 'Оплачено')], default='в ожидании', max_length=20)),
            ],
        ),
    ]
